// DAY DETECTION USING SWITCH case

let day = "4";

    switch (day)
     {
    case "1":
    console.log("Today is Monday");
    break;

    case "2":
    console.log("Today is Tuesday");
    break;

    case "3":
        console.log("Today is wednesday");
        break;

    case "4":
        console.log("Today is Thursday");
        break;

    case "5":
    console.log("Today is friday");
    break;

    case "6":
    console.log("Today is saturday");
    break;

    case "7":
    console.log("Today is sunday");
    break;

    default:
    console.log("error");
    }